spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS CARDPLATFORM
    username: sa
    password:
    hikari:
      schema: CARDPLATFORM
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:liquibase/changelog/changelog-master.yml
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
logging:
  level:
    com.cardplatform: DEBUG
    org.springframework.transaction: DEBUG
    liquibase: DEBUG