spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: cardplatform
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
logging:
  level:
    com.cardplatform: INFO
    org.jooq: INFO